const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { execFileSync, spawnSync } = require('node:child_process');

test('installed consumer resolves the pinned bundle and rejects drift before importing it', t => {
  const parent = process.env.MARC_TEST_ARTIFACTS || os.tmpdir();
  fs.mkdirSync(parent, { recursive: true });
  const root = fs.mkdtempSync(path.join(parent, 'marc-install-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const bundle = path.join(root, 'bundle'), consumer = path.join(root, 'consumer');
  const source = path.resolve(__dirname, '../..');
  for (const directory of ['src/quality', 'skills', 'scripts', 'templates'])
    fs.cpSync(path.join(source, directory), path.join(bundle, directory), { recursive: true });
  fs.mkdirSync(consumer);
  const git = (cwd, ...args) => execFileSync('git', args, { cwd, encoding: 'utf8', windowsHide: true, stdio: 'pipe' }).trim();
  git(bundle, 'init'); git(bundle, 'add', '.');
  git(bundle, '-c', 'core.hooksPath=', '-c', 'user.name=Synthetic test', '-c', 'user.email=test@example.invalid', 'commit', '-m', 'fixture');
  const pin = git(bundle, 'rev-parse', 'HEAD');
  git(consumer, 'init');
  git(consumer, '-c', 'protocol.file.allow=always', 'submodule', 'add', bundle, '.marc/tool');
  fs.cpSync(path.join(source, 'examples/python/.marc'), path.join(consumer, '.marc'), { recursive: true });
  const run = (...args) => execFileSync(process.execPath, args, { cwd: consumer, encoding: 'utf8', windowsHide: true, stdio: 'pipe' }).trim();
  const installer = path.join(bundle, 'scripts/install-consumer.cjs');
  const plan = JSON.parse(run(installer, '--repo', consumer));
  assert.equal(plan.applied, false); assert.equal(fs.existsSync(path.join(consumer, 'scripts/quality/bundle.cjs')), false);
  assert.equal(JSON.parse(run(installer, '--repo', consumer, '--apply')).applied, true);
  const resolved = JSON.parse(run('scripts/quality/marc.cjs', '--repo', consumer, 'config'));
  assert.equal(resolved.policy.repository, 'example/python-project');
  assert.equal(resolved.toolCommit, pin);
  assert.equal(resolved.bundleRoot, path.join(consumer, '.marc/tool'));
  const info = JSON.parse(run('scripts/quality/bundle.cjs'));
  assert.equal(info.commit, pin); assert.equal(fs.existsSync(path.join(info.skills, 'marc/SKILL.md')), true);
  const file = path.join(consumer, '.marc/config.json'), contents = fs.readFileSync(file, 'utf8');
  fs.writeFileSync(file, JSON.stringify({ ...JSON.parse(contents), toolCommit: 'b'.repeat(40) }));
  assert.throws(() => run('scripts/quality/bundle.cjs'), /match toolCommit/);
  fs.writeFileSync(file, contents);
  const runtime = path.join(consumer, '.marc/tool/src/quality/marc.cjs');
  const installedBytes = fs.readFileSync(runtime);
  fs.appendFileSync(runtime, '\nthrow Error("candidate must never execute");\n');
  const rejected = spawnSync(process.execPath, ['scripts/quality/marc.cjs', 'config'], { cwd: consumer, encoding: 'utf8', windowsHide: true });
  assert.notEqual(rejected.status, 0); assert.match(rejected.stderr, /match toolCommit/);
  assert.doesNotMatch(rejected.stderr, /candidate must never execute/);
  fs.writeFileSync(runtime, installedBytes);
  git(consumer, 'update-index', '--cacheinfo', `160000,${'c'.repeat(40)},.marc/tool`);
  assert.throws(() => run('scripts/quality/bundle.cjs'), /Git pin differs/);
});
